# eureka:
#   client:
#     registerWithEureka: true
#     fetchRegistry: true
#     service-url:
#       defaultZone: http://discovery:8761/eureka
#   instance:
#     prefer-ip-address: true
#     instance-id: testlocalhost:${server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8010/eureka}
  instance:
    preferIpAddress: true
