eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/ok
  instance:
    prefer-ip-address: true
    instance-id: testlocalhost:${server.port}
